# Generated by Django 6.0.2 on 2026-02-05 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('token', models.SlugField(max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='eventos/portadas/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Momento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('emoji', models.CharField(default='✨', max_length=5)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentos', to='memories.evento')),
            ],
            options={
                'verbose_name': 'Momento',
                'verbose_name_plural': 'Momentos',
                'ordering': ['orden', 'id'],
                'unique_together': {('evento', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='eventos/fotos/%Y/%m/%d/')),
                ('nombre_invitado', models.CharField(blank=True, max_length=80)),
                ('mensaje', models.CharField(blank=True, max_length=200)),
                ('visible', models.BooleanField(default=True)),
                ('destacada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='memories.evento')),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='memories.momento')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
