# Generated by Django 6.0.2 on 2026-02-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='owner_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
