# Generated by Django 6.0.2 on 2026-04-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_asistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='nombre_busqueda',
            field=models.CharField(blank=True, db_index=True, max_length=250),
        ),
        migrations.AddField(
            model_name='asistente',
            name='referencia',
            field=models.CharField(blank=True, help_text='Ejemplo: Familia Pérez, Mesa 3, amiga del colegio, etc.', max_length=120),
        ),
    ]
