# Generated by Django 6.0.2 on 2026-05-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_asistente_nombre_busqueda_asistente_referencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistente',
            options={'ordering': ['nombres'], 'verbose_name': 'Asistente', 'verbose_name_plural': 'Asistentes'},
        ),
        migrations.RenameField(
            model_name='asistente',
            old_name='numero_pases',
            new_name='adultos',
        ),
        migrations.RenameField(
            model_name='asistente',
            old_name='pases_confirmados',
            new_name='adultos_confirmados',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='referencia',
        ),
        migrations.AddField(
            model_name='asistente',
            name='estado_confirmacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asiste', 'Asiste'), ('no_asiste', 'No asistira')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='asistente',
            name='ninos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asistente',
            name='ninos_confirmados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='nombres',
            field=models.CharField(max_length=180),
        ),
    ]
